version: "3.9"

services:
  backend:
    build: ./backend
    container_name: petpath-backend-dev
    ports:
      - "5001:5001"
    env_file:
      - ./backend/config/.env
    restart: always
    volumes:
      - ./backend:/app
    networks:
      - petpath-network


  frontend:
    build: ./frontend
    container_name: petpath-frontend-dev
    ports:
      - "3001:3000"
    depends_on:
      - backend
    restart: always
    volumes:
      - ./frontend:/app
    networks:
      - petpath-network

networks:
  petpath-network:
    driver: bridge
